//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name can&apos;t be empty.
        /// </summary>
        public static string EmptyDomainName {
            get {
                return ResourceManager.GetString("EmptyDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO code can&apos;t be empty.
        /// </summary>
        public static string EmptyIsoCode {
            get {
                return ResourceManager.GetString("EmptyIsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		     Version 1, February 1989
        ///
        /// Copyright (C) 1989 Free Software Foundation, Inc.
        ///	            51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
        ///
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The license agreements of most software companies try to keep users
        ///at the mercy of those companies.  By contrast, our General Public
        ///License is intended to guarantee you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GPLv1 {
            get {
                return ResourceManager.GetString("GPLv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guarantee your freedom  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GPLv2 {
            get {
                return ResourceManager.GetString("GPLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GPLv3 {
            get {
                return ResourceManager.GetString("GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal binary character.
        /// </summary>
        public static string IllegalBinaryCharacter {
            get {
                return ResourceManager.GetString("IllegalBinaryCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters count.
        /// </summary>
        public static string InvalidCharacterCount {
            get {
                return ResourceManager.GetString("InvalidCharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        public static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member name.
        /// </summary>
        public static string InvalidMemberName {
            get {
                return ResourceManager.GetString("InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		  GNU LESSER GENERAL PUBLIC LICENSE
        ///		       Version 2.1, February 1999
        ///
        /// Copyright (C) 1991, 1999 Free Software Foundation, Inc.
        /// 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///[This is the first released version of the Lesser GPL.  It also counts
        /// as the successor of the GNU Library Public License, version 2, hence
        /// the version number 2.1.]
        ///
        ///			    Preamble        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LGPLv2 {
            get {
                return ResourceManager.GetString("LGPLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		   GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///
        ///  This version of the GNU Lesser General Public License incorporates
        ///the terms and conditions of version 3 of the GNU General Public
        ///License, supplemented by the additional permissions listed below.
        ///
        ///  0. Additional Defin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LGPLv3 {
            get {
                return ResourceManager.GetString("LGPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law. A &quot;contribution&quot; is the original software, or any additions or changes to the software. A &quot;contributor&quot; is any person that distributes its contribution under this [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MsPL {
            get {
                return ResourceManager.GetString("MsPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Reciprocal License (Ms-RL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        /// The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        /// A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        /// A &quot;contributor&quot; is any person that distributes its contribution u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MsRL {
            get {
                return ResourceManager.GetString("MsRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enought frames in stack trace.
        /// </summary>
        public static string NotEnoughtStackFrames {
            get {
                return ResourceManager.GetString("NotEnoughtStackFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd number of characters.
        /// </summary>
        public static string OddCharacterCount {
            get {
                return ResourceManager.GetString("OddCharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown top level domain.
        /// </summary>
        public static string UnknownTopLevelDomain {
            get {
                return ResourceManager.GetString("UnknownTopLevelDomain", resourceCulture);
            }
        }
    }
}
