//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0}{1}.
        /// </summary>
        internal static string CacheCookieFound {
            get {
                return ResourceManager.GetString("CacheCookieFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not do multi-file drop!.
        /// </summary>
        internal static string CanNotDoMultiFileDrop {
            get {
                return ResourceManager.GetString("CanNotDoMultiFileDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Language.
        /// </summary>
        internal static string CodeLanguage {
            get {
                return ResourceManager.GetString("CodeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Path ({0}) could not be created.  Please modify it in the Settings..
        /// </summary>
        internal static string CompilePathCouldNotBeCreated {
            get {
                return ResourceManager.GetString("CompilePathCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Error: {0}.
        /// </summary>
        internal static string CompilerError {
            get {
                return ResourceManager.GetString("CompilerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Errors.
        /// </summary>
        internal static string CompilerErrors {
            get {
                return ResourceManager.GetString("CompilerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile successful, but can&apos;t find {0}.
        /// </summary>
        internal static string CompileSuccessfulButCantFind {
            get {
                return ResourceManager.GetString("CompileSuccessfulButCantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling completed with no errors.
        /// </summary>
        internal static string CompilingCompletedWithNoErrors {
            get {
                return ResourceManager.GetString("CompilingCompletedWithNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling completed with no errors, running now.
        /// </summary>
        internal static string CompilingCompletedWithNoErrorsRunningNow {
            get {
                return ResourceManager.GetString("CompilingCompletedWithNoErrorsRunningNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling Script....
        /// </summary>
        internal static string CompilingScript {
            get {
                return ResourceManager.GetString("CompilingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Requested.
        /// </summary>
        internal static string ConfirmationRequested {
            get {
                return ResourceManager.GetString("ConfirmationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string ConfirmationRequired {
            get {
                return ResourceManager.GetString("ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all {0} items?.
        /// </summary>
        internal static string DeleteAllItems {
            get {
                return ResourceManager.GetString("DeleteAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} checked items?.
        /// </summary>
        internal static string DeleteCheckedItems {
            get {
                return ResourceManager.GetString("DeleteCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} Cache Entries.
        /// </summary>
        internal static string DeletedCacheEntries {
            get {
                return ResourceManager.GetString("DeletedCacheEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} Cache Entries from
        ///{1}.
        /// </summary>
        internal static string DeletedCacheEntriesFromPath {
            get {
                return ResourceManager.GetString("DeletedCacheEntriesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} Cookies.
        /// </summary>
        internal static string DeletedCookies {
            get {
                return ResourceManager.GetString("DeletedCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} Cookies from {1}.
        /// </summary>
        internal static string DeletedCookiesFromPath {
            get {
                return ResourceManager.GetString("DeletedCookiesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected items?.
        /// </summary>
        internal static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM Error Highlighting.
        /// </summary>
        internal static string DOMErrorHighlighting {
            get {
                return ResourceManager.GetString("DOMErrorHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an unsaved script, and loading will erase it.  Erase and continue loading?.
        /// </summary>
        internal static string EraseAndContinueLoading {
            get {
                return ResourceManager.GetString("EraseAndContinueLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4} [{0}] at Line {1} Column {2}: {3}.
        /// </summary>
        internal static string ErrorLineListing {
            get {
                return ResourceManager.GetString("ErrorLineListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors compiling your script:
        ///{0}.
        /// </summary>
        internal static string ErrorsCompilingYourScript {
            get {
                return ResourceManager.GetString("ErrorsCompilingYourScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error.
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find {0}.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Page.
        /// </summary>
        internal static string FindInPage {
            get {
                return ResourceManager.GetString("FindInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches.
        /// </summary>
        internal static string FoundMatches {
            get {
                return ResourceManager.GetString("FoundMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Explorer - {0}.
        /// </summary>
        internal static string FunctionExplorer {
            get {
                return ResourceManager.GetString("FunctionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Password.
        /// </summary>
        internal static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ietoolbar {
            get {
                object obj = ResourceManager.GetObject("ietoolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Bug.
        /// </summary>
        internal static string KnownBug {
            get {
                return ResourceManager.GetString("KnownBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart to change languges.  Do that now?.
        /// </summary>
        internal static string LanguageChange {
            get {
                return ResourceManager.GetString("LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of resources:.
        /// </summary>
        internal static string ListOfResources {
            get {
                return ResourceManager.GetString("ListOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded code is in a different code language..
        /// </summary>
        internal static string LoadedCodeInDifferentLang {
            get {
                return ResourceManager.GetString("LoadedCodeInDifferentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully.
        /// </summary>
        internal static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary code files could not be found..
        /// </summary>
        internal static string NecessaryCodeFilesCouldNotBeFound {
            get {
                return ResourceManager.GetString("NecessaryCodeFilesCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Default.
        /// </summary>
        internal static string NoDefault {
            get {
                return ResourceManager.GetString("NoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default template has been selected.  Please select from the list..
        /// </summary>
        internal static string NoDefaultTemplateSelected {
            get {
                return ResourceManager.GetString("NoDefaultTemplateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found.
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matches found for {0}.
        /// </summary>
        internal static string NoMoreMatchesFound {
            get {
                return ResourceManager.GetString("NoMoreMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests to compile.
        /// </summary>
        internal static string NoTestsToCompile {
            get {
                return ResourceManager.GetString("NoTestsToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests to run.
        /// </summary>
        internal static string NoTestsToRun {
            get {
                return ResourceManager.GetString("NoTestsToRun", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap progress_spinner {
            get {
                object obj = ResourceManager.GetObject("progress_spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://watintestrecord.sourceforge.net/TestRecorderInterfaces.html.
        /// </summary>
        internal static string RecorderHelpURL {
            get {
                return ResourceManager.GetString("RecorderHelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all cache entries?.
        /// </summary>
        internal static string RemoveAllCacheEntries {
            get {
                return ResourceManager.GetString("RemoveAllCacheEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to remove all cookies?.
        /// </summary>
        internal static string RemoveAllCookies {
            get {
                return ResourceManager.GetString("RemoveAllCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to remove all History entries?.
        /// </summary>
        internal static string RemoveAllHistory {
            get {
                return ResourceManager.GetString("RemoveAllHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove cache entries from {0} ?.
        /// </summary>
        internal static string RemoveCacheEntriesFromPath {
            get {
                return ResourceManager.GetString("RemoveCacheEntriesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove cookies from {0} ?.
        /// </summary>
        internal static string RemoveCookiesFromPath {
            get {
                return ResourceManager.GetString("RemoveCookiesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error - Not Saved.
        /// </summary>
        internal static string SaveErrorNotSaved {
            get {
                return ResourceManager.GetString("SaveErrorNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google.com/search?q={0}&amp;btnG=Google+Search&amp;meta=.
        /// </summary>
        internal static string SearchURL {
            get {
                return ResourceManager.GetString("SearchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Send cancelled.
        /// </summary>
        internal static string SendCanceled {
            get {
                return ResourceManager.GetString("SendCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mail Error.
        /// </summary>
        internal static string SendMailError {
            get {
                return ResourceManager.GetString("SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An HTML Dialog cannot be tracked by this application.
        ///If you know someone at Microsoft who can change this, we&apos;d love to support it. (MSDN KB251128)
        ///
        ///Continue opening the page?.
        /// </summary>
        internal static string showDialogBug {
            get {
                return ResourceManager.GetString("showDialogBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some items cannot be found, preventing compilation.  Please find these resources:.
        /// </summary>
        internal static string SomeItemsCannotBeFound {
            get {
                return ResourceManager.GetString("SomeItemsCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target template is set not to compile.
        /// </summary>
        internal static string TargetTemplateIsSetNotToCompile {
            get {
                return ResourceManager.GetString("TargetTemplateIsSetNotToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Source - {0}.
        /// </summary>
        internal static string Test_Source_Tab {
            get {
                return ResourceManager.GetString("Test_Source_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test name can contain only A-Z and 0-9.
        /// </summary>
        internal static string TestNameCanContainOnlyAZAnd09 {
            get {
                return ResourceManager.GetString("TestNameCanContainOnlyAZAnd09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Recorder Code (*.trc)|*.trc.
        /// </summary>
        internal static string TestRecorderCodeType {
            get {
                return ResourceManager.GetString("TestRecorderCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests must have a name..
        /// </summary>
        internal static string TestsMustHaveAName {
            get {
                return ResourceManager.GetString("TestsMustHaveAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Unknown Item .
        /// </summary>
        internal static string UnknownItem {
            get {
                return ResourceManager.GetString("UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your script is unsaved.  Continue closing?.
        /// </summary>
        internal static string UnsavedScript {
            get {
                return ResourceManager.GetString("UnsavedScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Script.
        /// </summary>
        internal static string UnsavedScript_title {
            get {
                return ResourceManager.GetString("UnsavedScript_title", resourceCulture);
            }
        }
    }
}
