//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.UnitTests.Test_Ozasmt._SampleScans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleScans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleScans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.UnitTests.Test_Ozasmt._SampleScans.SampleScans", typeof(SampleScans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;ThreatList&gt;
        ///    &lt;Threat&gt;System.Data.Sql&lt;/Threat&gt;
        ///    &lt;Description&gt;Locating where a database may be involved in the code is an important aspect of the code review. Looking at the database code will help determinate if the application is vulnerable to SQL Injection. One aspect of this is to verify that the code uses either SqlParameter, OleDbParameter or OdbcParameter(System.Data.SqlClient). These are type and treats parameter as the literal valu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CodeCrawler_SqlServerEngine_cs {
            get {
                return ResourceManager.GetString("CodeCrawler_SqlServerEngine_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;BugCollection version=&quot;1.3.8-dev-20090210&quot; sequence=&quot;0&quot; timestamp=&quot;1238713630000&quot; analysisTimestamp=&quot;1242168199859&quot; release=&quot;&quot;&gt;
        ///  &lt;Project filename=&quot;&amp;lt;&amp;lt;unnamed project&amp;gt;&amp;gt;&quot; projectName=&quot;WebGoat&quot;&gt;
        ///    &lt;Jar&gt;E:\_AppsToScan\Done\webgoat\_Ounce_6_0_Application\webgoat_compiled.zip.jar&lt;/Jar&gt;
        ///    &lt;SrcDir&gt;E:\_AppsToScan\Done\webgoat\_Ounce_6_0_Application\webgoat_compiled\JavaSource&lt;/SrcDir&gt;
        ///    &lt;SrcDir&gt;E:\_AppsToScan\Done\webgoat\_Ounce_6_0_Application\webgoat_comp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FindBugs_WebGoat {
            get {
                return ResourceManager.GetString("FindBugs_WebGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FVDL xmlns=&quot;xmlns://www.fortifysoftware.com/schema/fvdl1.3&quot;
        ///    xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; version=&quot;1.2&quot;&gt;
        ///&lt;!--&lt;FVDL&gt;--&gt;
        ///  &lt;CreatedTS date=&quot;2005-09-22&quot; time=&quot;10:19:53&quot;/&gt;
        ///  &lt;Build&gt;
        ///    &lt;NumberFiles&gt;9&lt;/NumberFiles&gt;
        ///    &lt;LOC&gt;2899&lt;/LOC&gt;
        ///    &lt;SourceBasePath&gt;/home/jw/Research/SecureProgrammingWorkshop/Examples/stunnel-3.13&lt;/SourceBasePath&gt;
        ///  &lt;/Build&gt;
        ///  &lt;Vulnerabilities&gt;
        ///    &lt;Vulnerability&gt;
        ///      &lt;ClassInfo&gt;
        ///        &lt;ClassID&gt;635A356B-CF51-420F-956E- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fortify_stunnel_3_13 {
            get {
                return ResourceManager.GetString("Fortify_stunnel_3_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;AssessmentRun&gt;
        ///	&lt;AssessmentStats class_total=&quot;28&quot; date=&quot;1237597549&quot; duration=&quot;0&quot; error_status=&quot;0&quot; language_type=&quot;2&quot; line_total=&quot;1455&quot; max_vdensity=&quot;30335.395189&quot; max_vkloc=&quot;100.343643&quot; method_total=&quot;150&quot; total_call_sites=&quot;514&quot; total_call_sites_informational=&quot;62&quot; total_call_sites_not_vulnerable=&quot;64&quot; total_files=&quot;25&quot; total_findings=&quot;276&quot; total_high_finding=&quot;43&quot; total_high_high_finding=&quot;42&quot; total_high_low_finding=&quot;0&quot; total_high_med_finding=&quot;1&quot; total_low_finding=&quot;87&quot; to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleScan_Ozasmt_6_0 {
            get {
                return ResourceManager.GetString("SampleScan_Ozasmt_6_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;AssessmentRun name=&quot;foo2 -  3/2/09 4:51PM&quot; version=&quot;6.1.0&quot;&gt;
        ///	&lt;AssessmentStats class_total=&quot;29&quot; date=&quot;1236030680&quot; duration=&quot;0&quot; error_status=&quot;0&quot; language_type=&quot;2&quot; line_total=&quot;1482&quot; max_vdensity=&quot;3296.221323&quot; max_vkloc=&quot;47.233468&quot; method_total=&quot;153&quot; total_call_sites=&quot;530&quot; total_call_sites_informational=&quot;58&quot; total_call_sites_not_vulnerable=&quot;72&quot; total_excluded_findings=&quot;92&quot; total_files=&quot;26&quot; total_findings=&quot;203&quot; total_high_finding=&quot;49&quot; total_high_high_finding=&quot;0&quot; total_hi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleScan_Ozasmt_6_1 {
            get {
                return ResourceManager.GetString("SampleScan_Ozasmt_6_1", resourceCulture);
            }
        }
    }
}
