// This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace O2.AppScan.AppScanDE.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class taintResultSet {
        
        private taintResultSetTaintResult[] taintResultField;
        
        private System.DateTime scanStartTimeField;
        
        private System.DateTime scanEndTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaintResult")]
        public taintResultSetTaintResult[] TaintResult {
            get {
                return this.taintResultField;
            }
            set {
                this.taintResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime scanStartTime {
            get {
                return this.scanStartTimeField;
            }
            set {
                this.scanStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime scanEndTime {
            get {
                return this.scanEndTimeField;
            }
            set {
                this.scanEndTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class taintResultSetTaintResult {
        
        private taintResultSetTaintResultTaintSource taintSourceField;
        
        private taintResultSetTaintResultTaintStep[] taintStepField;
        
        private taintResultSetTaintResultTaintSink taintSinkField;
        
        private int idField;
        
        private string ruleIDField;
        
        private string issueIDField;
        
        private string userSeverityField;
        
        /// <remarks/>
        public taintResultSetTaintResultTaintSource taintSource {
            get {
                return this.taintSourceField;
            }
            set {
                this.taintSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taintStep")]
        public taintResultSetTaintResultTaintStep[] taintStep {
            get {
                return this.taintStepField;
            }
            set {
                this.taintStepField = value;
            }
        }
        
        /// <remarks/>
        public taintResultSetTaintResultTaintSink taintSink {
            get {
                return this.taintSinkField;
            }
            set {
                this.taintSinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ruleID {
            get {
                return this.ruleIDField;
            }
            set {
                this.ruleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string issueID {
            get {
                return this.issueIDField;
            }
            set {
                this.issueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userSeverity {
            get {
                return this.userSeverityField;
            }
            set {
                this.userSeverityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class taintResultSetTaintResultTaintSource {
        
        private object snippetTextField;
        
        private string fileNameField;
        
        private string packageNameField;
        
        private string classNameField;
        
        private string methodNameField;
        
        private string methodSignatureField;
        
        private bool isPossibleSanitizerField;
        
        /// <remarks/>
        public object snippetText {
            get {
                return this.snippetTextField;
            }
            set {
                this.snippetTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodSignature {
            get {
                return this.methodSignatureField;
            }
            set {
                this.methodSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isPossibleSanitizer {
            get {
                return this.isPossibleSanitizerField;
            }
            set {
                this.isPossibleSanitizerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class taintResultSetTaintResultTaintStep {
        
        private string snippetTextField;
        
        private taintResultSetTaintResultTaintStepHighlight highlightField;
        
        private string fileNameField;
        
        private string projectNameField;
        
        private string packageNameField;
        
        private string classNameField;
        
        private string methodNameField;
        
        private string methodSignatureField;
        
        private ushort lineNumberField;
        
        private ushort snippetStartLineField;
        
        private bool isPossibleSanitizerField;
        
        private bool hasMappingField;
        
        private string rawFileNameField;
        
        private string rawClassNameField;
        
        private int rawLineNumberField;
        
        private bool rawLineNumberFieldSpecified;
        
        /// <remarks/>
        public string snippetText {
            get {
                return this.snippetTextField;
            }
            set {
                this.snippetTextField = value;
            }
        }
        
        /// <remarks/>
        public taintResultSetTaintResultTaintStepHighlight highlight {
            get {
                return this.highlightField;
            }
            set {
                this.highlightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodSignature {
            get {
                return this.methodSignatureField;
            }
            set {
                this.methodSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort snippetStartLine {
            get {
                return this.snippetStartLineField;
            }
            set {
                this.snippetStartLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isPossibleSanitizer {
            get {
                return this.isPossibleSanitizerField;
            }
            set {
                this.isPossibleSanitizerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hasMapping {
            get {
                return this.hasMappingField;
            }
            set {
                this.hasMappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rawFileName {
            get {
                return this.rawFileNameField;
            }
            set {
                this.rawFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rawClassName {
            get {
                return this.rawClassNameField;
            }
            set {
                this.rawClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rawLineNumber {
            get {
                return this.rawLineNumberField;
            }
            set {
                this.rawLineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rawLineNumberSpecified {
            get {
                return this.rawLineNumberFieldSpecified;
            }
            set {
                this.rawLineNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class taintResultSetTaintResultTaintStepHighlight {
        
        private ushort lineNumberField;
        
        private string colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class taintResultSetTaintResultTaintSink {
        
        private object snippetTextField;
        
        private string fileNameField;
        
        private string packageNameField;
        
        private string classNameField;
        
        private string methodNameField;
        
        private string methodSignatureField;
        
        private bool isPossibleSanitizerField;
        
        /// <remarks/>
        public object snippetText {
            get {
                return this.snippetTextField;
            }
            set {
                this.snippetTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string methodSignature {
            get {
                return this.methodSignatureField;
            }
            set {
                this.methodSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isPossibleSanitizer {
            get {
                return this.isPossibleSanitizerField;
            }
            set {
                this.isPossibleSanitizerField = value;
            }
        }
    }
}
