//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.External.IKVM.ScriptSamples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JavaSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavaSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.External.IKVM.ScriptSamples.JavaSamples", typeof(JavaSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import cli.O2.Kernel.PublicDI;
        ///import cli.O2.Kernel.Interfaces.*;
        ///import cli.O2.DotNetWrappers.O2Findings.*;
        ///import cli.O2.ImportExport.OunceLabs.Ozasmt_OunceV6.*;
        ///import cli.O2.Kernel.Interfaces.O2Findings.TraceType;
        ///
        ///
        ///class CreateFinding
        ///{  
        ///	public static void main(String args[])
        ///	{
        ///		System.out.println(&quot;!!Creating Custom finding file using O2&quot;);
        ///		
        ///		String o2KernelDll = PublicDI.get_config().get_O2KernelAssemblyName();
        ///		
        ///		System.out.println(&quot;This is an O2 call from Java: &quot; +  o2KernelD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateFinding_java {
            get {
                return ResourceManager.GetString("CreateFinding_java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class helloWorld
        ///{  
        ///	public static void main(String args[])
        ///	{
        ///		System.out.println(&quot;Hello World!&quot;);
        ///	}
        ///}.
        /// </summary>
        public static string helloWorld_java {
            get {
                return ResourceManager.GetString("helloWorld_java", resourceCulture);
            }
        }
    }
}
