// This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Tool.FindingsQuery._ScriptSamples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OzasmtScriptSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OzasmtScriptSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Tool.FindingsQuery._ScriptSamples.OzasmtScriptSamples", typeof(OzasmtScriptSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Windows.Forms;
        ///using O2.External.WinFormsUI.Forms;
        ///using O2.Views.ASCX.O2Findings;
        ///using O2.ImportExport.OunceLabs.Ozasmt_OunceV6; //O2_ImportExport_OunceLabs.dll
        ///
        ///namespace O2.Tool.OzasmtQuery._ScriptSamples
        ///{
        ///    public class A_OzasmtManipulation
        ///    {        
        ///        private const string ozasmtFileToUse = @&quot;E:\O2\Demodata\WebGoat 6.0_Scan_CurrentRules.ozasmt&quot;;
        ///            
        ///        private const string findingsViewerControlName_Source = &quot;Findings Viewer Source Data&quot;;
        ///     
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string A_OzamtManipulation {
            get {
                return ResourceManager.GetString("A_OzamtManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///using O2.Kernel;
        ///
        ///namespace O2.Tool.OzasmtQuery._ScriptSamples
        ///{
        ///    public class B_LinqExamples
        ///    {
        ///        public void linqeExample()
        ///        {
        ///            PublicDI.log.info(&quot;This is a linq example&quot;);
        ///        }
        ///    }
        ///}.
        /// </summary>
        public static string B_LinqExamples {
            get {
                return ResourceManager.GetString("B_LinqExamples", resourceCulture);
            }
        }
    }
}
