//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace O2.Legacy.CoreLib.resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources_Icons
    {
        private static CultureInfo resourceCulture;
        private static ResourceManager resourceMan;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Icons()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new ResourceManager("o2.core.resources.Resources_Icons",
                                                   typeof (Resources_Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Icon addApplication
        {
            get
            {
                object obj = ResourceManager.GetObject("addApplication", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_close
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_close", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_delete
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_delete", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_open
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_open", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_publish
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_publish", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_publishded
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_publishded", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_rename
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_rename", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_save
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_save", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Assessment_saveAs
        {
            get
            {
                object obj = ResourceManager.GetObject("Assessment_saveAs", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon AssessmentDiff
        {
            get
            {
                object obj = ResourceManager.GetObject("AssessmentDiff", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Bundles
        {
            get
            {
                object obj = ResourceManager.GetObject("Bundles", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Bundles_add
        {
            get
            {
                object obj = ResourceManager.GetObject("Bundles_add", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Bundles_delete
        {
            get
            {
                object obj = ResourceManager.GetObject("Bundles_delete", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Bundles_rename
        {
            get
            {
                object obj = ResourceManager.GetObject("Bundles_rename", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon CollapseAll
        {
            get
            {
                object obj = ResourceManager.GetObject("CollapseAll", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Console
        {
            get
            {
                object obj = ResourceManager.GetObject("Console", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Console_scrollLock
        {
            get
            {
                object obj = ResourceManager.GetObject("Console_scrollLock", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon CustomRules
        {
            get
            {
                object obj = ResourceManager.GetObject("CustomRules", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon CustomRules_Add
        {
            get
            {
                object obj = ResourceManager.GetObject("CustomRules_Add", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon CustomRules_Delete
        {
            get
            {
                object obj = ResourceManager.GetObject("CustomRules_Delete", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon DuplicateProject
        {
            get
            {
                object obj = ResourceManager.GetObject("DuplicateProject", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_copy
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_copy", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_cut
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_cut", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_find
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_find", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_FindNext
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_FindNext", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_paste
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_paste", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_Preferences
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_Preferences", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_remove
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_remove", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Edit_SelectAll
        {
            get
            {
                object obj = ResourceManager.GetObject("Edit_SelectAll", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Excluded_Findings
        {
            get
            {
                object obj = ResourceManager.GetObject("Excluded_Findings", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ExpandAll
        {
            get
            {
                object obj = ResourceManager.GetObject("ExpandAll", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer_allApplications
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer_allApplications", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer_Application
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer_Application", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer_File
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer_File", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer_Folder
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer_Folder", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Explorer_Project
        {
            get
            {
                object obj = ResourceManager.GetObject("Explorer_Project", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter_Add
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter_Add", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter_delete
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter_delete", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter_Manage
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter_Manage", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter_save
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter_save", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Filter_Share
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter_Share", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon FilterAssessment
        {
            get
            {
                object obj = ResourceManager.GetObject("FilterAssessment", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon FindingDetail
        {
            get
            {
                object obj = ResourceManager.GetObject("FindingDetail", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_API
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_API", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_applyFilter
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_applyFilter", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Bundle
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Bundle", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Filter
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Filter", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_High
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_High", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Info
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Info", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Medium
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Medium", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_SmartAudit_Info
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_SmartAudit_Info", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_SmartAudit_NoResults
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_SmartAudit_NoResults", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Table
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Table", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_TypeI
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_TypeI", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_TypeII
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_TypeII", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_Vulnerability
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_Vulnerability", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_VulnType
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_VulnType", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_withoutScan
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_withoutScan", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Findings_withScan
        {
            get
            {
                object obj = ResourceManager.GetObject("Findings_withScan", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon FixedMissedFindings
        {
            get
            {
                object obj = ResourceManager.GetObject("FixedMissedFindings", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon GenerateFindingsReport
        {
            get
            {
                object obj = ResourceManager.GetObject("GenerateFindingsReport", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon GenerateSmartAuditReport
        {
            get
            {
                object obj = ResourceManager.GetObject("GenerateSmartAuditReport", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon help
        {
            get
            {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Log_clearConsole
        {
            get
            {
                object obj = ResourceManager.GetObject("Log_clearConsole", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Log_OpenConsole
        {
            get
            {
                object obj = ResourceManager.GetObject("Log_OpenConsole", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_pinConsole
        {
            get
            {
                object obj = ResourceManager.GetObject("log_pinConsole", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_properties
        {
            get
            {
                object obj = ResourceManager.GetObject("log_properties", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_SaveFindings
        {
            get
            {
                object obj = ResourceManager.GetObject("log_SaveFindings", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_Search
        {
            get
            {
                object obj = ResourceManager.GetObject("log_Search", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_Showall
        {
            get
            {
                object obj = ResourceManager.GetObject("log_Showall", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon log_showErrors
        {
            get
            {
                object obj = ResourceManager.GetObject("log_showErrors", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Metrics
        {
            get
            {
                object obj = ResourceManager.GetObject("Metrics", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ModifiedFindings
        {
            get
            {
                object obj = ResourceManager.GetObject("ModifiedFindings", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon MySql
        {
            get
            {
                object obj = ResourceManager.GetObject("MySql", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon MySql_2
        {
            get
            {
                object obj = ResourceManager.GetObject("MySql_2", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon MySql_Administrator
        {
            get
            {
                object obj = ResourceManager.GetObject("MySql_Administrator", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon NewApplication
        {
            get
            {
                object obj = ResourceManager.GetObject("NewApplication", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon OpenAssessment
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenAssessment", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon OpenInExternalEditor
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenInExternalEditor", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon OpenInInternalEditor
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenInInternalEditor", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon PatternLibrary
        {
            get
            {
                object obj = ResourceManager.GetObject("PatternLibrary", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon PatternLibrary_Add
        {
            get
            {
                object obj = ResourceManager.GetObject("PatternLibrary_Add", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon PatternLibrary_Delete
        {
            get
            {
                object obj = ResourceManager.GetObject("PatternLibrary_Delete", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon PatternLibrary_Edit
        {
            get
            {
                object obj = ResourceManager.GetObject("PatternLibrary_Edit", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Preferences
        {
            get
            {
                object obj = ResourceManager.GetObject("Preferences", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Prespective_Analyzis
        {
            get
            {
                object obj = ResourceManager.GetObject("Prespective_Analyzis", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Prespective_Configuration
        {
            get
            {
                object obj = ResourceManager.GetObject("Prespective_Configuration", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Prespective_Triage
        {
            get
            {
                object obj = ResourceManager.GetObject("Prespective_Triage", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Project_excludedSourceRoot
        {
            get
            {
                object obj = ResourceManager.GetObject("Project_excludedSourceRoot", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Project_save
        {
            get
            {
                object obj = ResourceManager.GetObject("Project_save", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Project_saveProperties
        {
            get
            {
                object obj = ResourceManager.GetObject("Project_saveProperties", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon project_sourceRoot
        {
            get
            {
                object obj = ResourceManager.GetObject("project_sourceRoot", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ProjectProperties
        {
            get
            {
                object obj = ResourceManager.GetObject("ProjectProperties", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon refresh_active
        {
            get
            {
                object obj = ResourceManager.GetObject("refresh_active", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon refresh_grayedout
        {
            get
            {
                object obj = ResourceManager.GetObject("refresh_grayedout", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon RemediationAssistance
        {
            get
            {
                object obj = ResourceManager.GetObject("RemediationAssistance", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon RemoveProject
        {
            get
            {
                object obj = ResourceManager.GetObject("RemoveProject", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ScanAgain
        {
            get
            {
                object obj = ResourceManager.GetObject("ScanAgain", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ScanAll
        {
            get
            {
                object obj = ResourceManager.GetObject("ScanAll", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ScanCancel
        {
            get
            {
                object obj = ResourceManager.GetObject("ScanCancel", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ScanProject
        {
            get
            {
                object obj = ResourceManager.GetObject("ScanProject", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon ScanSelection
        {
            get
            {
                object obj = ResourceManager.GetObject("ScanSelection", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon Search
        {
            get
            {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon setConfiguration
        {
            get
            {
                object obj = ResourceManager.GetObject("setConfiguration", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon SmartAudit
        {
            get
            {
                object obj = ResourceManager.GetObject("SmartAudit", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon SmartTrace
        {
            get
            {
                object obj = ResourceManager.GetObject("SmartTrace", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon sort_ascending
        {
            get
            {
                object obj = ResourceManager.GetObject("sort_ascending", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon sort_descending
        {
            get
            {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon StartScan
        {
            get
            {
                object obj = ResourceManager.GetObject("StartScan", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Icon VulnerabilityMatrix
        {
            get
            {
                object obj = ResourceManager.GetObject("VulnerabilityMatrix", resourceCulture);
                return ((Icon) (obj));
            }
        }
    }
}