//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Legacy.CoreLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Legacy.CoreLib.Resources.Resources_Icons", typeof(Resources_Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon addApplication {
            get {
                object obj = ResourceManager.GetObject("addApplication", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_close {
            get {
                object obj = ResourceManager.GetObject("Assessment_close", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_delete {
            get {
                object obj = ResourceManager.GetObject("Assessment_delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_open {
            get {
                object obj = ResourceManager.GetObject("Assessment_open", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_publish {
            get {
                object obj = ResourceManager.GetObject("Assessment_publish", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_publishded {
            get {
                object obj = ResourceManager.GetObject("Assessment_publishded", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_rename {
            get {
                object obj = ResourceManager.GetObject("Assessment_rename", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_save {
            get {
                object obj = ResourceManager.GetObject("Assessment_save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Assessment_saveAs {
            get {
                object obj = ResourceManager.GetObject("Assessment_saveAs", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AssessmentDiff {
            get {
                object obj = ResourceManager.GetObject("AssessmentDiff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Bundles {
            get {
                object obj = ResourceManager.GetObject("Bundles", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Bundles_add {
            get {
                object obj = ResourceManager.GetObject("Bundles_add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Bundles_delete {
            get {
                object obj = ResourceManager.GetObject("Bundles_delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Bundles_rename {
            get {
                object obj = ResourceManager.GetObject("Bundles_rename", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon CollapseAll {
            get {
                object obj = ResourceManager.GetObject("CollapseAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Console {
            get {
                object obj = ResourceManager.GetObject("Console", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Console_scrollLock {
            get {
                object obj = ResourceManager.GetObject("Console_scrollLock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon CustomRules {
            get {
                object obj = ResourceManager.GetObject("CustomRules", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon CustomRules_Add {
            get {
                object obj = ResourceManager.GetObject("CustomRules_Add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon CustomRules_Delete {
            get {
                object obj = ResourceManager.GetObject("CustomRules_Delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon DuplicateProject {
            get {
                object obj = ResourceManager.GetObject("DuplicateProject", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_copy {
            get {
                object obj = ResourceManager.GetObject("Edit_copy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_cut {
            get {
                object obj = ResourceManager.GetObject("Edit_cut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_find {
            get {
                object obj = ResourceManager.GetObject("Edit_find", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_FindNext {
            get {
                object obj = ResourceManager.GetObject("Edit_FindNext", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_paste {
            get {
                object obj = ResourceManager.GetObject("Edit_paste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_Preferences {
            get {
                object obj = ResourceManager.GetObject("Edit_Preferences", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_remove {
            get {
                object obj = ResourceManager.GetObject("Edit_remove", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit_SelectAll {
            get {
                object obj = ResourceManager.GetObject("Edit_SelectAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Excluded_Findings {
            get {
                object obj = ResourceManager.GetObject("Excluded_Findings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ExpandAll {
            get {
                object obj = ResourceManager.GetObject("ExpandAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer_allApplications {
            get {
                object obj = ResourceManager.GetObject("Explorer_allApplications", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer_Application {
            get {
                object obj = ResourceManager.GetObject("Explorer_Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer_File {
            get {
                object obj = ResourceManager.GetObject("Explorer_File", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer_Folder {
            get {
                object obj = ResourceManager.GetObject("Explorer_Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Explorer_Project {
            get {
                object obj = ResourceManager.GetObject("Explorer_Project", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter_Add {
            get {
                object obj = ResourceManager.GetObject("Filter_Add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter_delete {
            get {
                object obj = ResourceManager.GetObject("Filter_delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter_Manage {
            get {
                object obj = ResourceManager.GetObject("Filter_Manage", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter_save {
            get {
                object obj = ResourceManager.GetObject("Filter_save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Filter_Share {
            get {
                object obj = ResourceManager.GetObject("Filter_Share", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FilterAssessment {
            get {
                object obj = ResourceManager.GetObject("FilterAssessment", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FindingDetail {
            get {
                object obj = ResourceManager.GetObject("FindingDetail", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings {
            get {
                object obj = ResourceManager.GetObject("Findings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_API {
            get {
                object obj = ResourceManager.GetObject("Findings_API", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_applyFilter {
            get {
                object obj = ResourceManager.GetObject("Findings_applyFilter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Bundle {
            get {
                object obj = ResourceManager.GetObject("Findings_Bundle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Filter {
            get {
                object obj = ResourceManager.GetObject("Findings_Filter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_High {
            get {
                object obj = ResourceManager.GetObject("Findings_High", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Info {
            get {
                object obj = ResourceManager.GetObject("Findings_Info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Medium {
            get {
                object obj = ResourceManager.GetObject("Findings_Medium", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_SmartAudit_Info {
            get {
                object obj = ResourceManager.GetObject("Findings_SmartAudit_Info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_SmartAudit_NoResults {
            get {
                object obj = ResourceManager.GetObject("Findings_SmartAudit_NoResults", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Table {
            get {
                object obj = ResourceManager.GetObject("Findings_Table", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_TypeI {
            get {
                object obj = ResourceManager.GetObject("Findings_TypeI", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_TypeII {
            get {
                object obj = ResourceManager.GetObject("Findings_TypeII", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_Vulnerability {
            get {
                object obj = ResourceManager.GetObject("Findings_Vulnerability", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_VulnType {
            get {
                object obj = ResourceManager.GetObject("Findings_VulnType", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_withoutScan {
            get {
                object obj = ResourceManager.GetObject("Findings_withoutScan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Findings_withScan {
            get {
                object obj = ResourceManager.GetObject("Findings_withScan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FixedMissedFindings {
            get {
                object obj = ResourceManager.GetObject("FixedMissedFindings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon GenerateFindingsReport {
            get {
                object obj = ResourceManager.GetObject("GenerateFindingsReport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon GenerateSmartAuditReport {
            get {
                object obj = ResourceManager.GetObject("GenerateSmartAuditReport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Log_clearConsole {
            get {
                object obj = ResourceManager.GetObject("Log_clearConsole", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Log_OpenConsole {
            get {
                object obj = ResourceManager.GetObject("Log_OpenConsole", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_pinConsole {
            get {
                object obj = ResourceManager.GetObject("log_pinConsole", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_properties {
            get {
                object obj = ResourceManager.GetObject("log_properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_SaveFindings {
            get {
                object obj = ResourceManager.GetObject("log_SaveFindings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_Search {
            get {
                object obj = ResourceManager.GetObject("log_Search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_Showall {
            get {
                object obj = ResourceManager.GetObject("log_Showall", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon log_showErrors {
            get {
                object obj = ResourceManager.GetObject("log_showErrors", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Metrics {
            get {
                object obj = ResourceManager.GetObject("Metrics", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ModifiedFindings {
            get {
                object obj = ResourceManager.GetObject("ModifiedFindings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon MySql {
            get {
                object obj = ResourceManager.GetObject("MySql", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon MySql_2 {
            get {
                object obj = ResourceManager.GetObject("MySql_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon MySql_Administrator {
            get {
                object obj = ResourceManager.GetObject("MySql_Administrator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon NewApplication {
            get {
                object obj = ResourceManager.GetObject("NewApplication", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon OpenAssessment {
            get {
                object obj = ResourceManager.GetObject("OpenAssessment", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon OpenInExternalEditor {
            get {
                object obj = ResourceManager.GetObject("OpenInExternalEditor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon OpenInInternalEditor {
            get {
                object obj = ResourceManager.GetObject("OpenInInternalEditor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PatternLibrary {
            get {
                object obj = ResourceManager.GetObject("PatternLibrary", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PatternLibrary_Add {
            get {
                object obj = ResourceManager.GetObject("PatternLibrary_Add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PatternLibrary_Delete {
            get {
                object obj = ResourceManager.GetObject("PatternLibrary_Delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PatternLibrary_Edit {
            get {
                object obj = ResourceManager.GetObject("PatternLibrary_Edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Preferences {
            get {
                object obj = ResourceManager.GetObject("Preferences", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Prespective_Analyzis {
            get {
                object obj = ResourceManager.GetObject("Prespective_Analyzis", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Prespective_Configuration {
            get {
                object obj = ResourceManager.GetObject("Prespective_Configuration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Prespective_Triage {
            get {
                object obj = ResourceManager.GetObject("Prespective_Triage", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Project_excludedSourceRoot {
            get {
                object obj = ResourceManager.GetObject("Project_excludedSourceRoot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Project_save {
            get {
                object obj = ResourceManager.GetObject("Project_save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Project_saveProperties {
            get {
                object obj = ResourceManager.GetObject("Project_saveProperties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon project_sourceRoot {
            get {
                object obj = ResourceManager.GetObject("project_sourceRoot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ProjectProperties {
            get {
                object obj = ResourceManager.GetObject("ProjectProperties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon refresh_active {
            get {
                object obj = ResourceManager.GetObject("refresh_active", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon refresh_grayedout {
            get {
                object obj = ResourceManager.GetObject("refresh_grayedout", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon RemediationAssistance {
            get {
                object obj = ResourceManager.GetObject("RemediationAssistance", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon RemoveProject {
            get {
                object obj = ResourceManager.GetObject("RemoveProject", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ScanAgain {
            get {
                object obj = ResourceManager.GetObject("ScanAgain", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ScanAll {
            get {
                object obj = ResourceManager.GetObject("ScanAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ScanCancel {
            get {
                object obj = ResourceManager.GetObject("ScanCancel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ScanProject {
            get {
                object obj = ResourceManager.GetObject("ScanProject", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ScanSelection {
            get {
                object obj = ResourceManager.GetObject("ScanSelection", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon setConfiguration {
            get {
                object obj = ResourceManager.GetObject("setConfiguration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SmartAudit {
            get {
                object obj = ResourceManager.GetObject("SmartAudit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SmartTrace {
            get {
                object obj = ResourceManager.GetObject("SmartTrace", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon sort_ascending {
            get {
                object obj = ResourceManager.GetObject("sort_ascending", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon sort_descending {
            get {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon StartScan {
            get {
                object obj = ResourceManager.GetObject("StartScan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon VulnerabilityMatrix {
            get {
                object obj = ResourceManager.GetObject("VulnerabilityMatrix", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
