//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.XRules.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XRules_Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XRules_Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.XRules.Database.XRules_Templates", typeof(XRules_Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.Views.ASCX;
        ///
        ///namespace O2.Script
        ///{
        ///    public class Empty_Class
        ///    {     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Empty_Class {
            get {
                return ResourceManager.GetString("Empty_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.Views.ASCX;
        ///using O2.Kernel.Interfaces.XRules;
        ///
        ///namespace O2.Script
        ///{
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Empty_XRule {
            get {
                return ResourceManager.GetString("Empty_XRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.ImportExport.OunceLabs.Ozasmt_Ou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Local_Findings_Files {
            get {
                return ResourceManager.GetString("Local_Findings_Files", resourceCulture);
            }
        }
    }
}
