//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace O2.ImportExport.Misc.Xsd
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BugCollection
    {

        private BugCollectionProject projectField;

        private BugCollectionBugInstance[] bugInstanceField;

        private BugCollectionErrors errorsField;

        private BugCollectionFindBugsSummary findBugsSummaryField;

        private object classFeaturesField;

        private object historyField;

        private string versionField;

        private byte sequenceField;

        private ulong timestampField;

        private ulong analysisTimestampField;

        private string releaseField;

        /// <remarks/>
        public BugCollectionProject Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BugInstance")]
        public BugCollectionBugInstance[] BugInstance
        {
            get
            {
                return this.bugInstanceField;
            }
            set
            {
                this.bugInstanceField = value;
            }
        }

        /// <remarks/>
        public BugCollectionErrors Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }

        /// <remarks/>
        public BugCollectionFindBugsSummary FindBugsSummary
        {
            get
            {
                return this.findBugsSummaryField;
            }
            set
            {
                this.findBugsSummaryField = value;
            }
        }

        /// <remarks/>
        public object ClassFeatures
        {
            get
            {
                return this.classFeaturesField;
            }
            set
            {
                this.classFeaturesField = value;
            }
        }

        /// <remarks/>
        public object History
        {
            get
            {
                return this.historyField;
            }
            set
            {
                this.historyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong analysisTimestamp
        {
            get
            {
                return this.analysisTimestampField;
            }
            set
            {
                this.analysisTimestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string release
        {
            get
            {
                return this.releaseField;
            }
            set
            {
                this.releaseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionProject
    {

        private string jarField;

        private string[] srcDirField;

        private BugCollectionProjectSuppressionFilter suppressionFilterField;

        private string filenameField;

        private string projectNameField;

        /// <remarks/>
        public string Jar
        {
            get
            {
                return this.jarField;
            }
            set
            {
                this.jarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SrcDir")]
        public string[] SrcDir
        {
            get
            {
                return this.srcDirField;
            }
            set
            {
                this.srcDirField = value;
            }
        }

        /// <remarks/>
        public BugCollectionProjectSuppressionFilter SuppressionFilter
        {
            get
            {
                return this.suppressionFilterField;
            }
            set
            {
                this.suppressionFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string projectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionProjectSuppressionFilter
    {

        private BugCollectionProjectSuppressionFilterLastVersion lastVersionField;

        /// <remarks/>
        public BugCollectionProjectSuppressionFilterLastVersion LastVersion
        {
            get
            {
                return this.lastVersionField;
            }
            set
            {
                this.lastVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionProjectSuppressionFilterLastVersion
    {

        private sbyte valueField;

        private string relOpField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relOp
        {
            get
            {
                return this.relOpField;
            }
            set
            {
                this.relOpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstance
    {

        private object[] itemsField;

        private string typeField;

        private byte priorityField;

        private string abbrevField;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class", typeof(BugCollectionBugInstanceClass))]
        [System.Xml.Serialization.XmlElementAttribute("Field", typeof(BugCollectionBugInstanceField))]
        [System.Xml.Serialization.XmlElementAttribute("Int", typeof(BugCollectionBugInstanceInt))]
        [System.Xml.Serialization.XmlElementAttribute("LocalVariable", typeof(BugCollectionBugInstanceLocalVariable))]
        [System.Xml.Serialization.XmlElementAttribute("Method", typeof(BugCollectionBugInstanceMethod))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(BugCollectionBugInstanceProperty))]
        [System.Xml.Serialization.XmlElementAttribute("SourceLine", typeof(BugCollectionBugInstanceSourceLine))]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(BugCollectionBugInstanceString))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(BugCollectionBugInstanceType))]
        [System.Xml.Serialization.XmlElementAttribute("UserAnnotation", typeof(object))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string abbrev
        {
            get
            {
                return this.abbrevField;
            }
            set
            {
                this.abbrevField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceClass
    {

        private BugCollectionBugInstanceClassSourceLine sourceLineField;

        private string classnameField;

        private string roleField;

        /// <remarks/>
        public BugCollectionBugInstanceClassSourceLine SourceLine
        {
            get
            {
                return this.sourceLineField;
            }
            set
            {
                this.sourceLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceClassSourceLine
    {

        private string classnameField;

        private string sourcefileField;

        private string sourcepathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcefile
        {
            get
            {
                return this.sourcefileField;
            }
            set
            {
                this.sourcefileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcepath
        {
            get
            {
                return this.sourcepathField;
            }
            set
            {
                this.sourcepathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceField
    {

        private BugCollectionBugInstanceFieldSourceLine sourceLineField;

        private string classnameField;

        private string nameField;

        private string signatureField;

        private bool isStaticField;

        /// <remarks/>
        public BugCollectionBugInstanceFieldSourceLine SourceLine
        {
            get
            {
                return this.sourceLineField;
            }
            set
            {
                this.sourceLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isStatic
        {
            get
            {
                return this.isStaticField;
            }
            set
            {
                this.isStaticField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceFieldSourceLine
    {

        private string classnameField;

        private string sourcefileField;

        private string sourcepathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcefile
        {
            get
            {
                return this.sourcefileField;
            }
            set
            {
                this.sourcefileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcepath
        {
            get
            {
                return this.sourcepathField;
            }
            set
            {
                this.sourcepathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceInt
    {

        private byte valueField;

        private string roleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceLocalVariable
    {

        private string nameField;

        private byte registerField;

        private ushort pcField;

        private string roleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort pc
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceMethod
    {

        private BugCollectionBugInstanceMethodSourceLine sourceLineField;

        private string classnameField;

        private string nameField;

        private string signatureField;

        private bool isStaticField;

        private string roleField;

        /// <remarks/>
        public BugCollectionBugInstanceMethodSourceLine SourceLine
        {
            get
            {
                return this.sourceLineField;
            }
            set
            {
                this.sourceLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isStatic
        {
            get
            {
                return this.isStaticField;
            }
            set
            {
                this.isStaticField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceMethodSourceLine
    {

        private string classnameField;

        private ushort startField;

        private bool startFieldSpecified;

        private ushort endField;

        private bool endFieldSpecified;

        private byte startBytecodeField;

        private bool startBytecodeFieldSpecified;

        private ushort endBytecodeField;

        private bool endBytecodeFieldSpecified;

        private string sourcefileField;

        private string sourcepathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified
        {
            get
            {
                return this.startFieldSpecified;
            }
            set
            {
                this.startFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endSpecified
        {
            get
            {
                return this.endFieldSpecified;
            }
            set
            {
                this.endFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte startBytecode
        {
            get
            {
                return this.startBytecodeField;
            }
            set
            {
                this.startBytecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startBytecodeSpecified
        {
            get
            {
                return this.startBytecodeFieldSpecified;
            }
            set
            {
                this.startBytecodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort endBytecode
        {
            get
            {
                return this.endBytecodeField;
            }
            set
            {
                this.endBytecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endBytecodeSpecified
        {
            get
            {
                return this.endBytecodeFieldSpecified;
            }
            set
            {
                this.endBytecodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcefile
        {
            get
            {
                return this.sourcefileField;
            }
            set
            {
                this.sourcefileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcepath
        {
            get
            {
                return this.sourcepathField;
            }
            set
            {
                this.sourcepathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceProperty
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceSourceLine
    {

        private string classnameField;

        private ushort startField;

        private ushort endField;

        private ushort startBytecodeField;

        private ushort endBytecodeField;

        private string sourcefileField;

        private string sourcepathField;

        private string roleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort startBytecode
        {
            get
            {
                return this.startBytecodeField;
            }
            set
            {
                this.startBytecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort endBytecode
        {
            get
            {
                return this.endBytecodeField;
            }
            set
            {
                this.endBytecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcefile
        {
            get
            {
                return this.sourcefileField;
            }
            set
            {
                this.sourcefileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcepath
        {
            get
            {
                return this.sourcepathField;
            }
            set
            {
                this.sourcepathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceString
    {

        private string valueField;

        private string roleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceType
    {

        private BugCollectionBugInstanceTypeSourceLine sourceLineField;

        private string descriptorField;

        private string roleField;

        /// <remarks/>
        public BugCollectionBugInstanceTypeSourceLine SourceLine
        {
            get
            {
                return this.sourceLineField;
            }
            set
            {
                this.sourceLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descriptor
        {
            get
            {
                return this.descriptorField;
            }
            set
            {
                this.descriptorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionBugInstanceTypeSourceLine
    {

        private string classnameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classname
        {
            get
            {
                return this.classnameField;
            }
            set
            {
                this.classnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionErrors
    {

        private string[] missingClassField;

        private byte errorsField;

        private byte missingClassesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MissingClass")]
        public string[] MissingClass
        {
            get
            {
                return this.missingClassField;
            }
            set
            {
                this.missingClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte missingClasses
        {
            get
            {
                return this.missingClassesField;
            }
            set
            {
                this.missingClassesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionFindBugsSummary
    {

        private BugCollectionFindBugsSummaryPackageStats[] packageStatsField;

        private BugCollectionFindBugsSummaryClassProfile[] findBugsProfileField;

        private string timestampField;

        private byte total_classesField;

        private ushort referenced_classesField;

        private ushort total_bugsField;

        private ushort total_sizeField;

        private byte num_packagesField;

        private string vm_versionField;

        private decimal cpu_secondsField;

        private decimal clock_secondsField;

        private decimal peak_mbytesField;

        private decimal alloc_mbytesField;

        private decimal gc_secondsField;

        private ushort priority_2Field;

        private byte priority_1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageStats")]
        public BugCollectionFindBugsSummaryPackageStats[] PackageStats
        {
            get
            {
                return this.packageStatsField;
            }
            set
            {
                this.packageStatsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ClassProfile", IsNullable = false)]
        public BugCollectionFindBugsSummaryClassProfile[] FindBugsProfile
        {
            get
            {
                return this.findBugsProfileField;
            }
            set
            {
                this.findBugsProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte total_classes
        {
            get
            {
                return this.total_classesField;
            }
            set
            {
                this.total_classesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort referenced_classes
        {
            get
            {
                return this.referenced_classesField;
            }
            set
            {
                this.referenced_classesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort total_bugs
        {
            get
            {
                return this.total_bugsField;
            }
            set
            {
                this.total_bugsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort total_size
        {
            get
            {
                return this.total_sizeField;
            }
            set
            {
                this.total_sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte num_packages
        {
            get
            {
                return this.num_packagesField;
            }
            set
            {
                this.num_packagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vm_version
        {
            get
            {
                return this.vm_versionField;
            }
            set
            {
                this.vm_versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cpu_seconds
        {
            get
            {
                return this.cpu_secondsField;
            }
            set
            {
                this.cpu_secondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal clock_seconds
        {
            get
            {
                return this.clock_secondsField;
            }
            set
            {
                this.clock_secondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal peak_mbytes
        {
            get
            {
                return this.peak_mbytesField;
            }
            set
            {
                this.peak_mbytesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal alloc_mbytes
        {
            get
            {
                return this.alloc_mbytesField;
            }
            set
            {
                this.alloc_mbytesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal gc_seconds
        {
            get
            {
                return this.gc_secondsField;
            }
            set
            {
                this.gc_secondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort priority_2
        {
            get
            {
                return this.priority_2Field;
            }
            set
            {
                this.priority_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority_1
        {
            get
            {
                return this.priority_1Field;
            }
            set
            {
                this.priority_1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionFindBugsSummaryPackageStats
    {

        private BugCollectionFindBugsSummaryPackageStatsClassStats[] classStatsField;

        private string packageField;

        private byte total_bugsField;

        private byte total_typesField;

        private ushort total_sizeField;

        private byte priority_2Field;

        private bool priority_2FieldSpecified;

        private byte priority_1Field;

        private bool priority_1FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClassStats")]
        public BugCollectionFindBugsSummaryPackageStatsClassStats[] ClassStats
        {
            get
            {
                return this.classStatsField;
            }
            set
            {
                this.classStatsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte total_bugs
        {
            get
            {
                return this.total_bugsField;
            }
            set
            {
                this.total_bugsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte total_types
        {
            get
            {
                return this.total_typesField;
            }
            set
            {
                this.total_typesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort total_size
        {
            get
            {
                return this.total_sizeField;
            }
            set
            {
                this.total_sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority_2
        {
            get
            {
                return this.priority_2Field;
            }
            set
            {
                this.priority_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priority_2Specified
        {
            get
            {
                return this.priority_2FieldSpecified;
            }
            set
            {
                this.priority_2FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority_1
        {
            get
            {
                return this.priority_1Field;
            }
            set
            {
                this.priority_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priority_1Specified
        {
            get
            {
                return this.priority_1FieldSpecified;
            }
            set
            {
                this.priority_1FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionFindBugsSummaryPackageStatsClassStats
    {

        private string classField;

        private string sourceFileField;

        private bool interfaceField;

        private ushort sizeField;

        private byte bugsField;

        private byte priority_2Field;

        private bool priority_2FieldSpecified;

        private byte priority_1Field;

        private bool priority_1FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceFile
        {
            get
            {
                return this.sourceFileField;
            }
            set
            {
                this.sourceFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @interface
        {
            get
            {
                return this.interfaceField;
            }
            set
            {
                this.interfaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte bugs
        {
            get
            {
                return this.bugsField;
            }
            set
            {
                this.bugsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority_2
        {
            get
            {
                return this.priority_2Field;
            }
            set
            {
                this.priority_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priority_2Specified
        {
            get
            {
                return this.priority_2FieldSpecified;
            }
            set
            {
                this.priority_2FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte priority_1
        {
            get
            {
                return this.priority_1Field;
            }
            set
            {
                this.priority_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priority_1Specified
        {
            get
            {
                return this.priority_1FieldSpecified;
            }
            set
            {
                this.priority_1FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BugCollectionFindBugsSummaryClassProfile
    {

        private string nameField;

        private ushort totalMillisecondsField;

        private uint invocationsField;

        private uint avgMicrosecondsPerInvocationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort totalMilliseconds
        {
            get
            {
                return this.totalMillisecondsField;
            }
            set
            {
                this.totalMillisecondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint invocations
        {
            get
            {
                return this.invocationsField;
            }
            set
            {
                this.invocationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint avgMicrosecondsPerInvocation
        {
            get
            {
                return this.avgMicrosecondsPerInvocationField;
            }
            set
            {
                this.avgMicrosecondsPerInvocationField = value;
            }
        }
    }
}