//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Core.FileViewers._UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Core.FileViewers._UnitTests.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///
        ///&lt;!DOCTYPE struts-config PUBLIC
        ///    &quot;-//Apache Software Foundation//DTD Struts Configuration 1.2//EN&quot;
        ///    &quot;http://jakarta.apache.org/struts/dtds/struts-config_1_2.dtd&quot;&gt;
        ///
        ///&lt;struts-config&gt;
        ///
        ///  &lt;form-beans&gt;
        ///    &lt;form-bean name=&quot;accountBean&quot; type=&quot;com.ibatis.jpetstore.presentation.AccountBean&quot;/&gt;
        ///    &lt;form-bean name=&quot;catalogBean&quot; type=&quot;com.ibatis.jpetstore.presentation.CatalogBean&quot;/&gt;
        ///    &lt;form-bean name=&quot;cartBean&quot; type=&quot;com.ibatis.jpetstore.presentation.CartB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ibatis_JPetstore_struts_config {
            get {
                return ResourceManager.GetString("Ibatis_JPetstore_struts_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///
        ///&lt;!DOCTYPE form-validation PUBLIC
        ///    &quot;-//Apache Software Foundation//DTD Commons Validator Rules Configuration 1.1.3//EN&quot;
        ///    &quot;http://jakarta.apache.org/commons/dtds/validator_1_1_3.dtd&quot;&gt;
        ///
        ///&lt;form-validation&gt;
        ///
        ///  &lt;formset&gt;
        ///
        ///    &lt;form name=&quot;/shop/newAccount&quot;&gt;
        ///      &lt;field
        ///          property=&quot;account.username&quot;
        ///          depends=&quot;required&quot;&gt;
        ///        &lt;arg key=&quot;account.username.label&quot;/&gt;
        ///      &lt;/field&gt;
        ///      &lt;field
        ///          property=&quot;account.password&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ibatis_JPetstore_validation {
            get {
                return ResourceManager.GetString("Ibatis_JPetstore_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;!DOCTYPE web-app
        ///    PUBLIC &quot;-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN&quot;
        ///    &quot;http://java.sun.com/dtd/web-app_2_3.dtd&quot;&gt;
        ///
        ///&lt;web-app version=&quot;2.4&quot; xmlns=&quot;http://java.sun.com/xml/ns/j2ee&quot;&gt;
        ///
        ///  &lt;display-name&gt;JPetStore&lt;/display-name&gt;
        ///  &lt;description&gt;Online Pet Store Sample Application&lt;/description&gt;
        ///
        ///  &lt;servlet&gt;
        ///    &lt;servlet-name&gt;action&lt;/servlet-name&gt;
        ///    &lt;servlet-class&gt;org.apache.struts.action.ActionServlet&lt;/servlet-class&gt;
        ///    &lt;init-param&gt;
        ///      &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ibatis_JPetstore_web {
            get {
                return ResourceManager.GetString("Ibatis_JPetstore_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!DOCTYPE struts-config PUBLIC
        ///          &quot;-//Apache Software Foundation//DTD Struts Configuration 1.1//EN&quot;
        ///          &quot;http://jakarta.apache.org/struts/dtds/struts-config_1_1.dtd&quot;&gt;
        ///
        ///&lt;struts-config&gt;
        ///
        ///	&lt;form-beans&gt;
        ///		&lt;form-bean name=&quot;accountForm&quot; type=&quot;org.springframework.samples.jpetstore.web.struts.AccountActionForm&quot;/&gt;
        ///		&lt;form-bean name=&quot;cartForm&quot; type=&quot;org.springframework.samples.jpetstore.web.struts.CartActionForm&quot;/&gt;
        ///		&lt;form-bean name=&quot;emptyForm&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Spring_JPetStore_struts_config {
            get {
                return ResourceManager.GetString("Spring_JPetStore_struts_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;web-app version=&quot;2.4&quot; xmlns=&quot;http://java.sun.com/xml/ns/j2ee&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///		xsi:schemaLocation=&quot;http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd&quot;&gt;
        ///
        ///	&lt;display-name&gt;Spring PetClinic&lt;/display-name&gt;
        ///
        ///	&lt;description&gt;Spring PetClinic sample application&lt;/description&gt;
        ///
        ///	&lt;!--
        ///		Key of the system property that should specify the root directory of this
        ///		web app. Applied by WebAppRootListener or Log4jCo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SpringMVC_PetClinic_web {
            get {
                return ResourceManager.GetString("SpringMVC_PetClinic_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;!--
        ///    Licensed to the Apache Software Foundation (ASF) under one or more
        ///    contributor license agreements.  See the NOTICE file distributed with
        ///    this work for additional information regarding copyright ownership.
        ///    The ASF licenses this file to You under the Apache License, Version 2.0
        ///    (the &quot;License&quot;); you may not use this file except in compliance with
        ///    the License.  You may obtain a copy of the License at
        ///   
        ///         http://www.apache [rest of string was truncated]&quot;;.
        /// </summary>
        public static string struts_sample_validation {
            get {
                return ResourceManager.GetString("struts_sample_validation", resourceCulture);
            }
        }
    }
}
