//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace O2.Core.CIR.Xsd
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class CommonIRDump
    {
        /// <remarks/>
        public CommonIRDumpCommonIR CommonIR { get; set; }

        /// <remarks/>
        [XmlArrayItem("ClassSymbols", IsNullable = false)]
        public CommonIRDumpClassSymbols[] SymbolData { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string DumpDateTime { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIR
    {
        /// <remarks/>
        [XmlElement("CompilationUnit")]
        public CommonIRDumpCommonIRCompilationUnit[] CompilationUnit { get; set; }

        /// <remarks/>
        [XmlElement("ClassMethods")]
        public CommonIRDumpCommonIRClassMethods[] ClassMethods { get; set; }

        /// <remarks/>
        [XmlElement("NonClassFunction")]
        public CommonIRDumpCommonIRNonClassFunction[] NonClassFunction { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRSignedInt8 SignedInt8 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRSignedInt16 SignedInt16 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRSignedInt32 SignedInt32 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRSignedInt64 SignedInt64 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRFloat32 Float32 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRFloat64 Float64 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRChar8 Char8 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRChar16 Char16 { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRBoolean Boolean { get; set; }

        /// <remarks/>
        public CommonIRDumpCommonIRVoid Void { get; set; }

        /// <remarks/>
        [XmlElement("FunctionSigType")]
        public CommonIRDumpCommonIRFunctionSigType[] FunctionSigType { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRCompilationUnit
    {
        /// <remarks/>
        public CommonIRDumpCommonIRCompilationUnitFile File { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRCompilationUnitFile
    {
        /// <remarks/>
        [XmlAttribute]
        public string Path { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRClassMethods
    {
        /// <remarks/>
        [XmlElement("ClassStaticFunction")]
        public CommonIRDumpCommonIRClassMethodsClassStaticFunction[] ClassStaticFunction { get; set; }

        /// <remarks/>
        [XmlElement("ClassMemberFunction")]
        public CommonIRDumpCommonIRClassMethodsClassMemberFunction[] ClassMemberFunction { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string ClassType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRClassMethodsClassStaticFunction
    {
        /// <remarks/>
        [XmlElement("Variable")]
        public Variable[] Variable { get; set; }

        /// <remarks/>
        public ControlFlowGraph ControlFlowGraph { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class Variable
    {
        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int GuaranteedInitBeforeUsed { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class ControlFlowGraph
    {
        /// <remarks/>
        [XmlElement("SsaVariable")]
        public ControlFlowGraphSsaVariable[] SsaVariable { get; set; }

        /// <remarks/>
        [XmlElement("BasicBlock")]
        public ControlFlowGraphBasicBlock[] BasicBlock { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphSsaVariable
    {
        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string BaseName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlock
    {
        /// <remarks/>
        [XmlElement("AssignmentStmt", typeof (ControlFlowGraphBasicBlockAssignmentStmt))]
        [XmlElement("CondBranchStmt", typeof (ControlFlowGraphBasicBlockCondBranchStmt))]
        [XmlElement("Edge", typeof (ControlFlowGraphBasicBlockEdge))]
        [XmlElement("EvalExprStmt", typeof (ControlFlowGraphBasicBlockEvalExprStmt))]
        [XmlElement("GotoStmt", typeof (ControlFlowGraphBasicBlockGotoStmt))]
        [XmlElement("PhiFunction", typeof (ControlFlowGraphBasicBlockPhiFunction))]
        [XmlElement("ReturnStmt", typeof (ControlFlowGraphBasicBlockReturnStmt))]
        [XmlElement("ThrowStmt", typeof (ControlFlowGraphBasicBlockThrowStmt))]
        public object[] Items { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Successors { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Predecessors { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string DominanceFrontier { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmt
    {
        /// <remarks/>
        [XmlElement("BinaryOprSubscript", typeof (ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscript))]
        [XmlElement("ConstVarAddress", typeof (ControlFlowGraphBasicBlockAssignmentStmtConstVarAddress))]
        [XmlElement("NaryCall", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCall))]
        [XmlElement("NaryCallVirtual", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtual))]
        [XmlElement("NaryOprNewArray", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewArray))]
        [XmlElement("NaryOprNewObject", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewObject))]
        [XmlElement("UnaryOprCast", typeof (ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCast))]
        [XmlElement("UnaryOprDereference", typeof (ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereference))]
        [XmlElement("UnaryOprField", typeof (ControlFlowGraphBasicBlockAssignmentStmtUnaryOprField))]
        [XmlElement("VarValue", typeof (ControlFlowGraphBasicBlockAssignmentStmtVarValue))]
        public object[] Items { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscript
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscriptVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscriptConstSignedInt32 ConstSignedInt32 { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscriptVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtBinaryOprSubscriptConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtConstVarAddress
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCall
    {
        /// <remarks/>
        [XmlElement("VarValue")]
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVarValue[] VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtual
    {
        /// <remarks/>
        [XmlElement("BinaryOprAdd", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAdd))]
        [XmlElement("ConstSignedInt32", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualConstSignedInt32)
            )]
        [XmlElement("UnaryOprCast", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCast))]
        [XmlElement("UnaryOprDereference",
            typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereference))]
        [XmlElement("VarValue", typeof (ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualVarValue))]
        public object[] Items { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAdd
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAddVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAddConstSignedInt32 ConstSignedInt32 { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAddVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualBinaryOprAddConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCast
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCastVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCastConstNarrowString ConstNarrowString { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCastVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprCastConstNarrowString
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereferenceUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryCallVirtualVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewArray
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewArrayConstSignedInt32 ConstSignedInt32 { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewArrayConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtNaryOprNewObject
    {
        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCast
    {
        /// <remarks/>
        public object ConstNull { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCastConstSignedInt32 ConstSignedInt32 { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCastVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCastConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprCastVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereferenceUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockAssignmentStmtUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockAssignmentStmtVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmt
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNE BinaryOprCompareNE { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQ BinaryOprCompareEQ { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int TrueEdgeIndex { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int TrueEdgeBasicBlock { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int FalseEdgeIndex { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int FalseEdgeBasicBlock { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNE
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEUnaryOprCast UnaryOprCast { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEConstSignedInt32 ConstSignedInt32 { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEUnaryOprCast
    {
        /// <remarks/>
        public object ConstNull { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareNEConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQ
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereference UnaryOprDereference { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCast UnaryOprCast { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQConstSignedInt32 ConstSignedInt32 { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereferenceUnaryOprFieldVarValue
            VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCast
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereference
            UnaryOprDereference { get; set; }

        /// <remarks/>
        public object ConstNull { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtual NaryCallVirtual { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereferenceUnaryOprField
            UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public
            ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereferenceUnaryOprFieldVarValue
            VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class
        ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtual
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualNaryCall NaryCall { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualNaryCall
    {
        /// <remarks/>
        public
            ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualNaryCallConstNarrowString
            ConstNarrowString { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class
        ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualNaryCallConstNarrowString
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQUnaryOprCastNaryCallVirtualVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockCondBranchStmtBinaryOprCompareEQConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEdge
    {
        /// <remarks/>
        [XmlAttribute]
        public int ExceptionEdge { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int SuccIndex { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int SuccBasicBlock { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int PredBasicBlock { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmt
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtual NaryCallVirtual { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCall NaryCall { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtual
    {
        /// <remarks/>
        [XmlElement("UnaryOprCast", typeof (ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprCast))]
        [XmlElement("UnaryOprDereference",
            typeof (ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereference))]
        [XmlElement("VarValue", typeof (ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualVarValue))]
        public object[] Items { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprCast
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprCastConstNarrowString ConstNarrowString { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprCastConstNarrowString
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereferenceUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVirtualVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCall
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallNaryOprNewObject NaryOprNewObject { get; set; }

        /// <remarks/>
        [XmlElement("VarValue")]
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallVarValue[] VarValue { get; set; }

        /// <remarks/>
        [XmlElement("UnaryOprCast")]
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCast[] UnaryOprCast { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereference UnaryOprDereference { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallNaryOprNewObject
    {
        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCast
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastConstNarrowString ConstNarrowString { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastConstFunctionAddress ConstFunctionAddress { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastConstNarrowString
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprCastConstFunctionAddress
    {
        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FunctionName { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereferenceUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockEvalExprStmtNaryCallUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockGotoStmt
    {
        /// <remarks/>
        [XmlAttribute]
        public int SuccessorEdgeIndex { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int SuccessorBasicBlock { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockPhiFunction
    {
        /// <remarks/>
        [XmlArrayItem("Variable", IsNullable = false)]
        public ControlFlowGraphBasicBlockPhiFunctionVariable[] PredecessorVariables { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string OriginalVariable { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string TargetSsaVariable { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockPhiFunctionVariable
    {
        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int GuaranteedInitBeforeUsed { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string DebugName { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmt
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtUnaryOprDereference UnaryOprDereference { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtUnaryOprCast UnaryOprCast { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int ReturnEdgeIndex { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int ReturnBasicBlock { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtUnaryOprDereference
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtUnaryOprDereferenceUnaryOprField UnaryOprField { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtUnaryOprDereferenceUnaryOprField
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtUnaryOprDereferenceUnaryOprFieldVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string FieldName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtUnaryOprDereferenceUnaryOprFieldVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtUnaryOprCast
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockReturnStmtUnaryOprCastVarValue VarValue { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtUnaryOprCastVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockReturnStmtVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Renamed { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockThrowStmt
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockThrowStmtVarValue VarValue { get; set; }

        /// <remarks/>
        public ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdge ThrowStmtCatchEdge { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public bool IsRethrow { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockThrowStmtVarValue
    {
        /// <remarks/>
        [XmlAttribute]
        public string VariableName { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdge
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdgePointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int CatchEdge { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdgePointerType
    {
        /// <remarks/>
        public ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdgePointerTypePointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ControlFlowGraphBasicBlockThrowStmtThrowStmtCatchEdgePointerTypePointerType
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRClassMethodsClassMemberFunction
    {
        /// <remarks/>
        [XmlElement("Variable")]
        public Variable[] Variable { get; set; }

        /// <remarks/>
        public ControlFlowGraph ControlFlowGraph { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRNonClassFunction
    {
        /// <remarks/>
        [XmlElement("Variable")]
        public Variable[] Variable { get; set; }

        /// <remarks/>
        public ControlFlowGraph ControlFlowGraph { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRSignedInt8
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRSignedInt16
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRSignedInt32
    {
        /// <remarks/>
        public CommonIRDumpCommonIRSignedInt32PointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRSignedInt32PointerType
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRSignedInt64
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRFloat32
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRFloat64
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRChar8
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRChar16
    {
        /// <remarks/>
        public CommonIRDumpCommonIRChar16PointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRChar16PointerType
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRBoolean
    {
        /// <remarks/>
        public CommonIRDumpCommonIRBooleanPointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRBooleanPointerType
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRVoid
    {
        /// <remarks/>
        public CommonIRDumpCommonIRVoidPointerType PointerType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRVoidPointerType
    {
        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRFunctionSigType
    {
        /// <remarks/>
        public CommonIRDumpCommonIRFunctionSigTypeReturnType ReturnType { get; set; }

        /// <remarks/>
        [XmlArrayItem("Argument", IsNullable = false)]
        public CommonIRDumpCommonIRFunctionSigTypeArgument[] ArgumentTypes { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRFunctionSigTypeReturnType
    {
        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpCommonIRFunctionSigTypeArgument
    {
        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbols
    {
        /// <remarks/>
        [XmlArrayItem("Superclass", IsNullable = false)]
        public CommonIRDumpClassSymbolsSuperclass[] Superclasses { get; set; }

        /// <remarks/>
        [XmlArrayItem("ClassField", IsNullable = false)]
        public CommonIRDumpClassSymbolsClassField[] ClassFields { get; set; }

        /// <remarks/>
        [XmlArrayItem("MemberField", IsNullable = false)]
        public CommonIRDumpClassSymbolsMemberField[] MemberFields { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolDef { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int Anonymous { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsSuperclass
    {
        /// <remarks/>
        [XmlAttribute]
        public string ClassType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassField
    {
        /// <remarks/>
        public CommonIRDumpClassSymbolsClassFieldConstFloat32 ConstFloat32 { get; set; }

        /// <remarks/>
        public CommonIRDumpClassSymbolsClassFieldUnaryOprCast UnaryOprCast { get; set; }

        /// <remarks/>
        public CommonIRDumpClassSymbolsClassFieldConstSignedInt64 ConstSignedInt64 { get; set; }

        /// <remarks/>
        public CommonIRDumpClassSymbolsClassFieldConstSignedInt32 ConstSignedInt32 { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string UniqueID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public int GuaranteedInitBeforeUsed { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassFieldConstFloat32
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassFieldUnaryOprCast
    {
        /// <remarks/>
        public CommonIRDumpClassSymbolsClassFieldUnaryOprCastConstNarrowString ConstNarrowString { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassFieldUnaryOprCastConstNarrowString
    {
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassFieldConstSignedInt64
    {
        /// <remarks/>
        [XmlAttribute]
        public long Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsClassFieldConstSignedInt32
    {
        /// <remarks/>
        [XmlAttribute]
        public int Value { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class CommonIRDumpClassSymbolsMemberField
    {
        /// <remarks/>
        [XmlAttribute]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PrintableType { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string SymbolRef { get; set; }
    }
}