//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.Cmd.FindingsFilter.Filters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.Cmd.FindingsFilter.Filters.CustomScripts", typeof(CustomScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using O2.Cmd.FindingsFilter.Ascx;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.External.WinFormsUI.Forms;
        ///using O2.Interfaces.O2Findings;
        ///
        ///namespace O2.Cmd.FindingsFilter.Filters
        ///{
        ///    public class JoinTraces
        ///    {
        ///    	priva [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JoinTraces {
            get {
                return ResourceManager.GetString("JoinTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.Interfaces.O2Findings;
        ///
        ///namespace O2.Cmd.FindingsFilter.Filters
        ///{
        ///    public class OzasmtFilters
        ///    {
        ///        
        ///        public static void onlyTraces(string ozasmtF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OzasmtFilters {
            get {
                return ResourceManager.GetString("OzasmtFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is part of the OWASP O2 Platform (http://www.owasp.org/index.php/OWASP_O2_Platform) and is released under the Apache 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Xml.Linq;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.External.WinFormsUI.Forms;
        ///using O2.Interfaces.O2Core;
        ///using O2.Interfaces.O2Findings;
        ///usi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string parse_Jsf_xHtml_Files {
            get {
                return ResourceManager.GetString("parse_Jsf_xHtml_Files", resourceCulture);
            }
        }
    }
}
