//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2.XRules.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XRules_RulesSourceCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XRules_RulesSourceCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2.XRules.Database.XRules_RulesSourceCode", typeof(XRules_RulesSourceCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///	[TestFixture]
        ///    public class Analysis_Workflow : KXRule
        ///    {    
        ///    	string testAnalysisArtifactsFile = @&quot;E:\O2\Demodata\_AnalysisWorkflow\WebGoat.AnalysisArtifacts&quot;;
        ///    	// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using System.Collections.Generic;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class Analysis_Workflow_Phase_1 : KXRule
        ///    {          	       
        ///       	//string testAnalysisArtifactsFile = @&quot;E:\O2\Demodata\_Analysi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow_Phase_1 {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow_Phase_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class Analysis_Workflow_Phase_2 : KXRule
        ///    {    
        ///    	//string testAnalysisArtifactsFile = @&quot;E: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow_Phase_2 {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow_Phase_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using System.Collections.Generic;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        /////O2Tag_AddSourceFile:E:\O2\_SourceCode_O2\O2_XRules_Database\Interfaces\IAnalysisArtifacts.cs
        /////O2Tag_AddSourceFile:E:\O2\_SourceCode_O2\O2_XRules_Database\Interfaces\KAnalysisArtifacts.cs
        ///
        ///namespac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow_Phase_3 {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow_Phase_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.XRules.Database._Rules;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class Analysis_Workflow_Phase_4 : KXRule
        ///    {        	 
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow_Phase_4 {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow_Phase_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class Analysis_Workflow_Phase_5 : KXRule
        ///    {        	 
        ///
        ///		//string testAnalysisArtifactsFile = @&quot;E:\O2\Demodata\_AnalysisWorkflow\WebGoat.AnalysisArtifacts&quot;;
        ///    	string testAnalysisA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analysis_WorkFlow_Phase_5 {
            get {
                return ResourceManager.GetString("Analysis_WorkFlow_Phase_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.XRules.Database.Interfaces;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class Sample_Analysis_Workflow_WebGoat : KXRule
        ///    {
        ///        private static IO2Log log = PublicDI.log;
        ///
        ///        public Sample_Analysis_Workflow_WebGoa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sample_Analysis_Workflow_WebGoat {
            get {
                return ResourceManager.GetString("Sample_Analysis_Workflow_WebGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.IO;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.Core.FileViewers.Struts_1_5;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    [TestFixture]
        ///    public class SampleScripts : KXRule
        ///    {    
        ///        private static IO2Log log = PublicDI.log;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleScripts {
            get {
                return ResourceManager.GetString("SampleScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.ImportExport.OunceLabs.Ozasmt_OunceV6;
        ///
        ///using O2.XRules.Database._Rules;
        /////O2Tag_AddReferenceFile:nunit.framework.dll
        ///using NUnit.Framework;
        ///
        ///namespace O2.XRules.v0_1
        ///{	
        ///	// Description: this sample show a number of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleUnitTests {
            get {
                return ResourceManager.GetString("SampleUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading;
        ///using O2.ImportExport.OunceLabs.Ozasmt_OunceV6;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.Kernel;
        ///using O2.Views.ASCX.O2Findings;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class XRule_Findings_Filter : KXRule
        ///    {
        ///        private readonly IO2Log log = PublicDI.log [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XRule_Findings_Filter {
            get {
                return ResourceManager.GetString("XRule_Findings_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using O2.Kernel;
        ///using System.Collections.Generic;
        ///using O2.Core.FileViewers.Ascx;
        ///using O2.Core.FileViewers.Ascx.O2Rules;
        ///using O2.Core.FileViewers.JoinTraces;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.External.WinFormsUI.Forms;
        ///using O2.Kernel.Interfaces.FrameworkSupport.J2EE;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.Views;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.Views.ASCX.O2Findings;
        ///
        ///namespace O2.XRules.Databas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XRule_Struts {
            get {
                return ResourceManager.GetString("XRule_Struts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using NUnit.Framework;
        ///using O2.DotNetWrappers.O2CmdShell;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class XUtils_Analysis
        ///    {
        ///        public static string createStrutsMappingsFromFilesIn(string folderWithConfigFiles, string targetFile)
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XUtils_Analysis {
            get {
                return ResourceManager.GetString("XUtils_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Text;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.XRules.Database.Interfaces;
        ///
        /////O2Tag_AddSourceFile:E:\O2\_SourceCode_O2\O2_XRules_Database\Interfaces\IAnalysisArtifacts.cs
        /////O2Tag_AddSourceFile:E:\O2\_SourceCode_O2\O2_XRules_Database\Interfaces\KA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XUtils_AnalysisWorkflow {
            get {
                return ResourceManager.GetString("XUtils_AnalysisWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using System.IO;
        ///using System.Threading;
        ///using O2.Core.FileViewers.JoinTraces;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.Windows;
        ///using O2.ImportExport.OunceLabs.Ozasmt_OunceV6;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Views.ASCX.O2Findings;
        ///
        ///namespace O2.XRules.Database._Rules
        ///{
        ///    public class XUtils_Findings_v0_1
        ///    {
        ///        private static read [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xUtils_Findings_v0_1 {
            get {
                return ResourceManager.GetString("xUtils_Findings_v0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using O2.Core.FileViewers.Ascx;
        ///using O2.Core.FileViewers.Ascx.O2Rules;
        ///using O2.Core.FileViewers.JoinTraces;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.External.WinFormsUI.Forms;
        ///using O2.Kernel;
        ///using O2.Kernel.Interfaces.FrameworkSupport.J2EE;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.Views;
        ///using O2.Views.ASCX.O2Findings;
        ///
        ////*public XRule_Struts() [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XUtils_Struts_Joins_V0_1 {
            get {
                return ResourceManager.GetString("XUtils_Struts_Joins_V0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using O2.Core.FileViewers.Ascx.O2Rules;
        ///using O2.Core.FileViewers.Struts_1_5;
        ///using O2.Kernel;
        ///using System.Threading;
        ///using O2.ImportExport.OunceLabs.Ozasmt_OunceV6;
        ///using O2.DotNetWrappers.O2Findings;
        ///using O2.DotNetWrappers.DotNet;
        ///using O2.Kernel.Interfaces.O2Findings;
        ///using O2.Kernel.Interfaces.O2Core;
        ///using O2.Kernel.Interfaces.Views;
        ///using O2.Kernel.Interfaces.XRules;
        ///using O2.Kernel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xUtils_Struts_v0_1 {
            get {
                return ResourceManager.GetString("xUtils_Struts_v0_1", resourceCulture);
            }
        }
    }
}
